# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: CocoaPods@0
  displayName: 'Install dependencies'
  inputs:
    forceRepoUpdate: false
- task: Xcode@5
  displayName: 'Building For iOS'
  inputs:
    actions: 'clean build'
    configuration: 'Debug'
    sdk: 'iphonesimulator'
    scheme: 'GooglePlaces'
    workingDirectory: 'GooglePlaces'
    xcWorkspacePath: 'GooglePlaces/GooglePlaces.xcworkspace'
    packageApp: false
    destinationPlatformOption: 'iOS'
    destinationSimulators: 'iPhone 8'