# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: CocoaPods@0
  displayName: 'Install dependencies'
  inputs:
    forceRepoUpdate: false
# - task: Xcode@5
#   inputs:
#     actions: 'build'
#     scheme: 'GooglePlaces'
#     sdk: 'iphoneos'
#     configuration: 'Debug'
#     xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
#     xcodeVersion: 'default' # Options: 8, 9, 10, default, specifyPath
- task: Xcode@5
  inputs:
    actions: 'clean build'
    configuration: 'Debug'
    sdk: 'iphonesimulator'
    scheme: 'GooglePlaces'
    packageApp: false
    destinationPlatformOption: 'iOS'
    destinationSimulators: 'iPhone 8'