# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :development do

    UI.message("\n\n\n=====================================\n Starting iOS build process \n=====================================")

    # increment_build_number(xcodeproj: "GooglePlaces.xcodeproj")

    UI.message("\n\n\n=====================================\n building ios app \n=====================================")

    build_app(workspace: "GooglePlaces.xcworkspace", 
    	configuration: "Debug",
  		scheme: "GooglePlaces",
  		export_options: {
    		method: "development"
  		},
  		silent: true,
  		clean: true,
  		output_directory: "path/to/dir", # Destination directory. Defaults to current directory.
  		output_name: "GooglePlaces.ipa",
    	xcargs: "-allowProvisioningUpdates")

    UI.message("\n\n\n=====================================\n uploading ios with dSYM files (not zipped) \n=====================================")
        
  # upload_to_testflight
  end
end
